# Generated by Django 3.2 on 2021-04-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('site_url', models.URLField(max_length=2000)),
                ('operating_hour', models.CharField(max_length=45)),
                ('latitude_x', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('longitude_y', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.location'),
        ),
    ]
