# Generated by Django 3.2 on 2021-04-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20210428_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='latitude_x',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='longitude_y',
        ),
    ]
