# Generated by Django 3.2 on 2021-04-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20210428_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude_x',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude_y',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='operating_hour',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
