# Generated by Django 3.2 on 2021-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20210429_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude_x',
            field=models.DecimalField(decimal_places=16, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude_y',
            field=models.DecimalField(decimal_places=16, max_digits=18),
        ),
    ]
