# Generated by Django 3.2 on 2021-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_auto_20210429_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='operating_hour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
