# Generated by Django 3.2 on 2021-04-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_auto_20210430_1316'),
        ('users', '0001_initial'),
        ('bids', '0007_auto_20210429_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finish_at', models.DateTimeField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art')),
            ],
            options={
                'db_table': 'biddings',
            },
        ),
        migrations.CreateModel(
            name='BiddingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bidding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'bidding_users',
            },
        ),
        migrations.AddField(
            model_name='bidding',
            name='user',
            field=models.ManyToManyField(through='bids.BiddingUser', to='users.User'),
        ),
    ]
