# Generated by Django 3.2 on 2021-04-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release_date', models.DateField()),
                ('thumbnail_url', models.URLField(max_length=2000)),
                ('views', models.PositiveBigIntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist')),
            ],
            options={
                'db_table': 'arts',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('link_url', models.URLField(max_length=2000)),
                ('text', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medium',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'styles',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='ArtTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.theme')),
            ],
            options={
                'db_table': 'art_themes',
            },
        ),
        migrations.CreateModel(
            name='ArtStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.style')),
            ],
            options={
                'db_table': 'art_styles',
            },
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.art')),
            ],
            options={
                'db_table': 'art_images',
            },
        ),
        migrations.CreateModel(
            name='ArtColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.color')),
            ],
            options={
                'db_table': 'art_colors',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='color',
            field=models.ManyToManyField(through='arts.ArtColor', to='arts.Color'),
        ),
        migrations.AddField(
            model_name='art',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.material'),
        ),
        migrations.AddField(
            model_name='art',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.media'),
        ),
        migrations.AddField(
            model_name='art',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.paper'),
        ),
        migrations.AddField(
            model_name='art',
            name='style',
            field=models.ManyToManyField(through='arts.ArtStyle', to='arts.Style'),
        ),
        migrations.AddField(
            model_name='art',
            name='theme',
            field=models.ManyToManyField(through='arts.ArtTheme', to='arts.Theme'),
        ),
    ]
