# Generated by Django 3.2 on 2021-04-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_theme_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'art_status',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.artstatus'),
        ),
    ]
