# Generated by Django 3.2 on 2021-04-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
