# Generated by Django 3.2 on 2021-05-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210502_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='framematerial',
            name='render_image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
